version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/workspace
    environment:
      - MONGO_URI=mongodb://db:27017/local_trivia
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=trivia_admin_secret_123
    depends_on:
      - db
    restart: always

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
